"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['keychecker.py']
DATA_FILES = ['logo.gif']
OPTIONS = {
	'includes': ['bitcoin', 'pyblake2', 'pysodium', 'appJar'],
	'iconfile': 'logo.icns',
    'plist': {
        'CFBundleName': "Tezos Contribution Checker",
        'CFBundleDisplayName': "Tezos Contribution Checker",
        'CFBundleGetInfoString': "Check your Tezos contribution details will give you access to your tokens on launch.",
        'CFBundleIdentifier': "com.erroneous.tezoschecker",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u""
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
